// Auth
export const APP_LOGIN = "APP_LOGIN";
export const APP_LOGOUT = "APP_LOGOUT";
export const APP_SET_AUTH_STATE = "app/setAuthState";
export const APP_SAVE_LOGGED_USER = "app/saveLoggedUser";
export const APP_REMOVE_LOGGED_USER = "app/removeLoggedUser";
export const APP_SAVE_REFRESH_TOKEN = "app/saveRefreshToken";
export const APP_REGISTER = "app/register";
export const APP_VERIFY_TOKEN = "app/verifyToken";

//app
export const ACTION_SEARCH = "ACTION_SEARCH";
export const COLLPSE_CHANGE = "COLLPSE_CHANGE";
export const TOGGLE_ALL = "TOGGLE_ALL";
export const DRAWER_OPEN_SIDEBAR = "DRAWER_OPEN_SIDEBAR";
export const CLOSE_DRAWER_OPEN_SIDEBAR = "CLOSE_DRAWER_OPEN_SIDEBAR";

// gửi dữ liệu 4 trạng thái
export const MARK_REQUEST_PENDING = "request/requestPending";
export const MARK_REQUEST_SUCCESS = "request/requestSuccess";
export const MARK_REQUEST_FAILURE = "request/requestFailure";
export const MARK_REQUEST_CANCELLED = "request/requestCancelled";

// invoke callback
export const INVOKE_CALLBACK = "app/invokeCallBack";

//user
export const GET_ALL_USER = "GET_ALL_USER";
export const SAVE_GET_ALL_USER = "SAVE_GET_ALL_USER";
export const DELL_USER = "DELL_USER";
export const SAVE_DELL_USER = "SAVE_DELL_USER";
export const GET_USER_WITH_ID = "GET_USER_WITH_ID";
export const SAVE_USER_WITH_ID = "SAVE_USER_WITH_ID";
export const ACTIVESTATUS = "ACTIVESTATUS";
export const INACTIVESTATUS = "INACTIVESTATUS";
export const CREATE_SINGLE_USER = "CREATE_SINGLE_USER";
export const UPDATE_SINGLE_USER = "UPDATE_SINGLE_USER";
export const SEARCH_USER = "SEARCH_USER";
export const SAVE_SEARCH_USER = "SAVE_SEARCH_USER";
export const DELL_IMG_SINGLE_USER = "DELL_IMG_SINGLE_USER";
export const CHANGE_PASSWORD_USER = "CHANGE_PASSWORD_USER";
export const UPLOAD_IMAGE_USER = "UPLOAD_IMAGE_USER";
export const SAVE_UPLOAD_IMAGE_USER = "SAVE_UPLOAD_IMAGE_USER";
export const CONFIRM_UPLOAD_IMAGE_USER = "CONFIRM_UPLOAD_IMAGE_USER";
export const PAGE_USERS = "PAGE_USERS"

//master
export const GET_ALL_MASTER = "GET_ALL_MASTER";
export const SAVE_GET_ALL_MASTER = "SAVE_GET_ALL_MASTER";
export const DELL_MASTER = "DELL_MASTER";
export const SAVE_DELL_MASTER = "SAVE_DELL_MASTER";
export const GET_MASTER_WITH_ID = "GET_MASTER_WITH_ID";
export const SAVE_MASTER_WITH_ID = "SAVE_MASTER_WITH_ID";
export const ACTIVE_STATUS_MASTER = "ACTIVE_STATUS_MASTER";
export const INACTIVE_STATUS_MASTER = "INACTIVE_STATUS_MASTER";
export const CREATE_SINGLE_MASTER = "CREATE_SINGLE_MASTER";
export const UPDATE_SINGLE_MASTER = "UPDATE_SINGLE_MASTER";
export const SEARCH_MASTER = "SEARCH_MASTER";
export const SAVE_SEARCH_MASTER = "SAVE_SEARCH_MASTER";
export const CHANGE_PASSWORD_MASTER = "CHANGE_PASSWORD_MASTER";
export const UPDATE_SINGLE_MASTER_CONTACT = "UPDATE_SINGLE_MASTER_CONTACT";
export const UPLOAD_IMAGE_MASTER = "UPLOAD_IMAGE_MASTER";
export const SAVE_UPLOAD_IMAGE_MASTER = "SAVE_UPLOAD_IMAGE_MASTER";
export const CONFIRM_UPLOAD_IMAGE_MASTER = "CONFIRM_UPLOAD_IMAGE_MASTER";
export const GET_ALL_SERVICE_MASTER = "GET_ALL_SERVICE_MASTER";
export const SAVE_SERVICE_MASTER = "SAVE_SERVICE_MASTER";
export const CREATE_SERVICE_MASTER = "CREATE_SERVICE_MASTER";
export const UPDATE_SERVICE_MASTER = "UPDATE_SERVICE_MASTER";
export const DELETE_SERVICE_MASTER = "DELETE_SERVICE_MASTER";
export const GET_ALL_MASTER_PROVINCES = 'GET_ALL_MASTER_PROVINCES'
export const SAVE_ALL_MASTER_PROVINCES = 'SAVE_ALL_MASTER_PROVINCES'
export const UPLOAD_IMAGE_MASTER_SERVICE = "UPLOAD_IMAGE_MASTER_SERVICE";
export const SAVE_UPLOAD_IMAGE_SERVICE = "SAVE_UPLOAD_IMAGE_SERVICE";
export const CONFIRM_UPLOAD_IMAGE_SERVICE = "CONFIRM_UPLOAD_IMAGE_SERVICE";
export const GET_ALL_DISTRICT = "GET_ALL_DISTRICT";
export const SAVE_ALL_DISTRICT = "SAVE_ALL_DISTRICT";
export const GET_ALL_WARD = "GET_ALL_WARD";
export const SAVE_ALL_WARD = "SAVE_ALL_WARD";
export const PAGE_MASTERS = "PAGE_MASTERS"




// news
export const GET_ALL_NEW = "GET_ALL_NEW";
export const SAVE_GET_ALL_NEW = "SAVE_GET_ALL_NEW";
export const DELL_NEW = "DELL_NEW";
export const SAVE_DELL_NEW = "SAVE_DELL_NEW";
export const CREATE_SINGLE_NEW = "CREATE_SINGLE_NEW";
export const UPDATE_SINGLE_NEW = "UPDATE_SINGLE_NEW";
export const GET_NEW_WITH_ID = "GET_NEW_WITH_ID";
export const SAVE_NEW_WITH_ID = "SAVE_NEW_WITH_ID";
// export const SEARCH_USER = "SEARCH_USER";
// export const SAVE_SEARCH_USER = "SAVE_SEARCH_USER";
export const UPLOAD_IMAGE_NEW = "UPLOAD_IMAGE_NEW";
export const SAVE_UPLOAD_IMAGE_NEW = "SAVE_UPLOAD_IMAGE_NEW";
export const CONFIRM_UPLOAD_IMAGE_BANNER_NEW =
  "CONFIRM_UPLOAD_IMAGE_BANNER_NEW";
  export const PAGE_NEWS = 'PAGE_NEWS'

// comments
export const GET_ALL_COMMENT = "GET_ALL_COMMENT";
export const SAVE_GET_ALL_COMMENT = "SAVE_GET_ALL_COMMENT";
export const DELL_COMMENT = "DELL_COMMENT";
export const SAVE_DELL_COMMENT = "SAVE_DELL_COMMENT";
export const CREATE_SINGLE_COMMENT = "CREATE_SINGLE_COMMENT";
export const UPDATE_SINGLE_COMMENT = "UPDATE_SINGLE_COMMENT";

// complaints
export const GET_ALL_COMPLAINTS = "GET_ALL_COMPLAINTS";
export const SAVE_GET_ALL_COMPLAINTS = "SAVE_GET_ALL_COMPLAINTS";
export const DELL_COMPLAINTS = "DELL_COMPLAINTS";
export const SAVE_DELL_COMPLAINTS = "SAVE_DELL_COMPLAINTS";
export const CREATE_SINGLE_COMPLAINTS = "CREATE_SINGLE_COMPLAINTS";
export const UPDATE_SINGLE_COMPLAINTS = "UPDATE_SINGLE_COMPLAINTS";
export const GET_COMPLAINTS_WITH_ID = "GET_COMPLAINTS_WITH_ID";
export const SAVE_COMPLAINTS_WITH_ID = "SAVE_COMPLAINTS_WITH_ID";
export const ANSWER_COMPLAINTS_USER = "ANSWER_COMPLAINTS_USER";

// ratings
export const GET_ALL_RATING = "GET_ALL_RATING";
export const SAVE_GET_ALL_RATING = "SAVE_GET_ALL_RATING";
export const DELL_RATING = "DELL_RATING";
export const SAVE_DELL_RATING = "SAVE_DELL_RATING";
export const CREATE_SINGLE_RATING = "CREATE_SINGLE_RATING";
export const UPDATE_SINGLE_RATING = "UPDATE_SINGLE_RATING";
export const GET_COMMENT_WITH_ID_RATE = "GET_COMMENT_WITH_ID_RATE";
export const SAVE_COMMENT_WITH_ID_RATE = "SAVE_COMMENT_WITH_ID_RATE";

//schedule
export const GET_ALL_SCHEDULE = "GET_ALL_SCHEDULE";
export const SAVE_GET_ALL_SCHEDULE = "SAVE_GET_ALL_SCHEDULE";
export const DELL_SCHEDULE = "DELL_SCHEDULE";
export const SAVE_DELL_SCHEDULE = "SAVE_DELL_SCHEDULE";
export const CREATE_SINGLE_SCHEDULE = "CREATE_SINGLE_SCHEDULE";
export const UPDATE_SINGLE_SCHEDULE = "UPDATE_SINGLE_SCHEDULE";

//faq
export const GET_ALL_FAQ = "GET_ALL_FAQ";
export const SAVE_GET_ALL_FAQ = "SAVE_GET_ALL_FAQ";
export const DELL_FAQ = "DELL_FAQ";
export const SAVE_DELL_FAQ = "SAVE_DELL_FAQ";
export const CREATE_SINGLE_FAQ = "CREATE_SINGLE_FAQ";
export const UPDATE_SINGLE_FAQ = "UPDATE_SINGLE_FAQ";
export const GET_FAQ_WITH_ID = "GET_FAQ_WITH_ID";
export const SAVE_FAQ_WITH_ID = "SAVE_FAQ_WITH_ID";
export const PAGE_FAQ = "PAGE_FAQ"

//recommend
export const GET_ALL_RECOMMEND = "GET_ALL_RECOMMEND";
export const SAVE_GET_ALL_RECOMMEND = "SAVE_GET_ALL_RECOMMEND";
export const DELL_RECOMMEND = "DELL_RECOMMEND";
export const SAVE_DELL_RECOMMEND = "SAVE_DELL_RECOMMEND";
export const CREATE_SINGLE_RECOMMEND = "CREATE_SINGLE_RECOMMEND";
export const UPDATE_SINGLE_RECOMMEND = "UPDATE_SINGLE_RECOMMEND";

//setting
export const GET_ALL_SETTING = "GET_ALL_SETTING";
export const SAVE_GET_ALL_SETTING = "SAVE_GET_ALL_SETTING";
export const DELL_SETTING = "DELL_SETTING";
export const SAVE_DELL_SETTING = "SAVE_DELL_SETTING";
export const CREATE_SINGLE_SETTING = "CREATE_SINGLE_SETTING";
export const UPDATE_SINGLE_SETTING = "UPDATE_SINGLE_SETTING";

//Modal
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

// Drawer
export const DRAWER_OPEN = "DRAWER_OPEN";
export const DRAWER_CLOSE = "DRAWER_CLOSE";
//FAQS
export const ADD_FAQ = "ADD_FAQ";

//Category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const SAVE_ALL_CATEGORY = "SAVE_ALL_CATEGORY";
export const DELL_CATEGORY = "DELL_CATEGORY";
export const SAVE_DELL_CATEGORY = "SAVE_DELL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORY_WITH_ID = "GET_CATEGORY_WITH_ID";
export const SAVE_CATEGORY_WITH_ID = "SAVE_CATEGORY_WITH_ID";
export const UPLOAD_IMAGE_CATEGORY = "UPLOAD_IMAGE_CATEGORY";
export const SAVE_UPLOAD_IMAGE_CATEGORY = "SAVE_UPLOAD_IMAGE_CATEGORY";
export const CONFIRM_UPLOAD_IMAGE_CATEGORY = "CONFIRM_UPLOAD_IMAGE_CATEGORY";

// Notification
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const SAVE_ALL_NOTIFICATION = "SAVE_ALL_NOTIFICATION";
export const DELL_NOTIFICATION = "DELL_NOTIFICATION";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const GET_NOTIFICATION_WITH_ID = "GET_NOTIFICATION_WITH_ID";
export const SAVE_NOTIFICATION_WITH_ID = "SAVE_NOTIFICATION_WITH_ID";

// Locations
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const GET_LOCATIONS_WITH_ID = "GET_LOCATIONS_WITH_ID";
export const UPLOAD_IMAGE_LOCATIONS = "UPLOAD_IMAGE_LOCATIONS";
export const CONFIRM_UPLOAD_IMAGE_LOCATIONS = "CONFIRM_UPLOAD_IMAGE_LOCATIONS";
export const SAVE_GET_ALL_LOCATIONS = "SAVE_GET_ALL_LOCATIONS";
export const SAVE_LOCATIONS_WITH_ID = "SAVE_LOCATIONS_WITH_ID";
export const SAVE_UPLOAD_IMAGE_LOCATIONS = "SAVE_UPLOAD_IMAGE_LOCATIONS";
export const PAGE_LOCATIONS = "PAGE_LOCATIONS"

// promotions
export const GET_ALL_PROMOTIONS = "GET_ALL_PROMOTIONS";
export const DELL_PROMOTIONS = "DELL_PROMOTIONS";
export const GET_PROMOTIONS_WITH_ID = "GET_PROMOTIONS_WITH_ID";
export const UPLOAD_IMAGE_PROMOTIONS = "UPLOAD_IMAGE_PROMOTIONS";
export const CREATE_SINGLE_PROMOTIONS = "CREATE_SINGLE_PROMOTIONS";
export const UPDATE_SINGLE_PROMOTIONS = "UPDATE_SINGLE_PROMOTIONS";
export const CONFIRM_UPLOAD_IMAGE_BANNER_PROMOTIONS =
  "CONFIRM_UPLOAD_IMAGE_BANNER_PROMOTIONS";

export const SAVE_PROMOTIONS_WITH_ID = "SAVE_PROMOTIONS_WITH_ID";
export const SAVE_UPLOAD_IMAGE_PROMOTIONS = "SAVE_UPLOAD_IMAGE_PROMOTIONS";
export const SAVE_DELL_PROMOTIONS = "SAVE_DELL_PROMOTIONS";
export const SAVE_GET_ALL_PROMOTIONS = "SAVE_GET_ALL_PROMOTIONS";
